---
- name: Install Klaus Vormweg repo
  apt_repository:
    repo: ppa:klaus-vormweg/awesome
    codename: 'xenial'
- name: Install awesomewm
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - libcairo-gobject2
    - awesome
    - awesome-extra
    - rxvt-unicode-256color
